#############################################################################
# Makefile for building: captureQt
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  captureQt.pro
# Template: app
# Command: /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -o Makefile captureQt.pro -spec devices/linux-rasp-pi4-v3d-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
CXX           = /opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a72 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a72 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt5pi/sysroot/include/opencv4 -I/opt/qt5pi/sysroot/include -I/opt/qt5pi/sysroot/usr/local/qt5pi/include -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQmlModels -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtNetwork -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore -I. -I. -I/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++
QMAKE         = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = captureQt1.0.0
DISTDIR = /home/marco/Devel/captureQt/captureQt/.tmp/captureQt1.0.0
LINK          = /opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/opt/qt5pi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/opt/qt5pi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/opt/qt5pi/sysroot/lib -lraspicam -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_videoio -lopencv_imgcodecs -lopencv_flann /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Quick.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Widgets.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Gui.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5QmlModels.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Qml.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Network.so /opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Core.so -L/opt/qt5pi/sysroot/usr/lib/arm-linux-gnueabihf -lGLESv2 -lpthread   
AR            = /opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++/qmake.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qtquickcompiler.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/uic.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf \
		captureQt.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = captureQt
DESTDIR       = 
TARGET        = captureQt


first: all
####### Build rules

captureQt: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: captureQt.pro /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++/qmake.conf /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++/qmake.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qtquickcompiler.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/uic.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf \
		captureQt.pro
	$(QMAKE) -o Makefile captureQt.pro -spec devices/linux-rasp-pi4-v3d-g++ CONFIG+=qtquickcompiler
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++/qmake.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources_functions.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qtquickcompiler.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/uic.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf:
captureQt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile captureQt.pro -spec devices/linux-rasp-pi4-v3d-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile captureQt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp
	/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a72 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtguiglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtcore-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlogging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qflags.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmutex.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtgui-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstring.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qchar.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringliteral.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringview.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiterator.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpair.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvector.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainertools_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpoint.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qregexp.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmargins.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrect.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsize.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpalette.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcolor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgb.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgba64.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qbrush.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qregion.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qline.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtransform.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qimage.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhash.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfont.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcursor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvariant.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdebug.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlocale.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qset.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfile.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qicon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QPainter \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainter.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtextoption.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpen.h \
		/opt/qt5pi/sysroot/include/raspicam/raspicam.h \
		/opt/qt5pi/sysroot/include/raspicam/raspicamtypes.h \
		moc_predefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/bin/moc
	/opt/qt5pi/sysroot/usr/local/qt5pi/bin/moc $(DEFINES) --include /home/marco/Devel/captureQt/captureQt/moc_predefs.h -I/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi4-v3d-g++ -I/home/marco/Devel/captureQt/captureQt -I/opt/qt5pi/sysroot/include/opencv4 -I/opt/qt5pi/sysroot/include -I/opt/qt5pi/sysroot/usr/local/qt5pi/include -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQmlModels -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtNetwork -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/7.5.0 -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/7.5.0/arm-linux-gnueabihf -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/7.5.0/backward -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/7.5.0/include -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/7.5.0/include-fixed -I/opt/qt5pi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/opt/qt5pi/sysroot/usr/include/arm-linux-gnueabihf -I/opt/qt5pi/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/opt/qt5pi/sysroot/usr/local/qt5pi/bin/uic
	/opt/qt5pi/sysroot/usr/local/qt5pi/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtguiglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtcore-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlogging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qflags.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmutex.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtgui-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstring.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qchar.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringliteral.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringview.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiterator.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpair.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvector.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainertools_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpoint.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qregexp.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmargins.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrect.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsize.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpalette.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcolor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgb.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgba64.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qbrush.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qregion.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qline.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtransform.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qimage.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhash.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfont.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcursor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvariant.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdebug.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlocale.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qset.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfile.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qicon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QPainter \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainter.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtextoption.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpen.h \
		/opt/qt5pi/sysroot/include/raspicam/raspicam.h \
		/opt/qt5pi/sysroot/include/raspicam/raspicamtypes.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/QApplication \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qapplication.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreapplication.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qeventloop.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qguiapplication.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QImage \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qimage.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtguiglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtcore-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlogging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qflags.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmutex.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtgui-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcolor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgb.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiterator.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstring.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qchar.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringliteral.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringview.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpair.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvector.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainertools_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpoint.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qregexp.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgba64.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrect.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmargins.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsize.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtransform.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qregion.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qline.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/opencv.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/opencv_modules.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cvdef.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/hal/interface.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/hal/msa_macros.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/fast_math.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/version.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/base.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cvstd.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/neon_utils.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/vsx_utils.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/check.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/traits.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/matx.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/saturate.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/types.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/mat.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/bufferpool.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/mat.inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/persistence.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/operations.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/utility.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/utils/tls.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/optim.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/ovx.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/calib3d.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/features2d.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/miniflann.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/defines.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/config.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/affine.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/dnn.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/async.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/version.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/dict.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/layer.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/flann_base.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/general.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/matrix.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/params.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/any.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/saving.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/nn_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/result_set.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/all_indices.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/kdtree_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/dist.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/heap.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/allocator.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/random.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/kmeans_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/logger.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/composite_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/linear_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/lsh_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/lsh_table.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/autotuned_index.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/ground_truth.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/index_testing.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/timer.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/flann/sampling.h \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/highgui.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/imgcodecs.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/videoio.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/imgproc.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/ml.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/ml/ml.inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/objdetect.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/photo.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/warpers.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cuda.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cuda_types.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/core/cuda.inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/util.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/video.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/video/tracking.hpp \
		/opt/qt5pi/sysroot/include/opencv4/opencv2/video/background_segm.hpp \
		/opt/qt5pi/sysroot/include/raspicam/raspicam.h \
		/opt/qt5pi/sysroot/include/raspicam/raspicamtypes.h \
		mainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpalette.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qbrush.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhash.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfont.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcursor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvariant.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdebug.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlocale.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qset.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfile.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qicon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QPainter \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainter.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtextoption.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpen.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pi/captureQt || mkdir -p $(INSTALL_ROOT)/home/pi/captureQt
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/pi/captureQt/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/pi/captureQt/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/pi/captureQt/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pi/captureQt/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

