#ifndef PINS_H
#define PINS_H

// BUZZER OUTPUT PIN
#define BUZZER_PIN 21
// SHUTTER BUTTON
#define SHUTTER_PIN 16
// ILLUMINATOR BUTTON
#define IRLEDSBTN_PIN 24
// IR LEDs ILLUMINATOR OUTPUT PIN
#define IRLEDS_PIN 23

#endif // PINS_H
